"""Initial migration

Revision ID: ae7755c29d78
Revises: 
Create Date: 2025-12-12 15:39:08.936578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7755c29d78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    op.create_table('papers',
    sa.Column('pmid', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('journal', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pmid')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_pmid', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_pmid'], ['papers.pmid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citations',
    sa.Column('citing_pmid', sa.String(length=20), nullable=False),
    sa.Column('cited_pmid', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cited_pmid'], ['papers.pmid'], ),
    sa.ForeignKeyConstraint(['citing_pmid'], ['papers.pmid'], ),
    sa.PrimaryKeyConstraint('citing_pmid', 'cited_pmid')
    )
    op.create_table('paper_authors',
    sa.Column('paper_pmid', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['paper_pmid'], ['papers.pmid'], ),
    sa.PrimaryKeyConstraint('paper_pmid', 'author_id')
    )
    op.create_table('paper_keywords',
    sa.Column('paper_pmid', sa.String(length=20), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['paper_pmid'], ['papers.pmid'], ),
    sa.PrimaryKeyConstraint('paper_pmid', 'keyword_id')
    )
    op.create_table('query_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_saved_papers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paper_pmid', sa.String(length=20), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['paper_pmid'], ['papers.pmid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'paper_pmid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_saved_papers')
    op.drop_table('query_logs')
    op.drop_table('paper_keywords')
    op.drop_table('paper_authors')
    op.drop_table('citations')
    op.drop_table('chunks')
    op.drop_table('users')
    op.drop_table('papers')
    op.drop_table('keywords')
    op.drop_table('authors')
    # ### end Alembic commands ###
